import { NativeModules } from 'react-native';

module.exports = {
		"volume": NativeModules.Volume,
		"wifi": NativeModules.Wifi,
		"bluetooth": NativeModules.Bluetooth,
		"brightness": NativeModules.Brightness,
		"files": NativeModules.Files,
		"alarm": NativeModules.Alarm,
		"image": NativeModules.Image,
		"video": NativeModules.Video,
		"audio": NativeModules.Audio,
		"sms": NativeModules.Sms,
		"calls": NativeModules.Calls,
		"contacts": NativeModules.Contacts,
		"Volume": NativeModules.Volume,
		"Wifi": NativeModules.Wifi,
		"Bluetooth": NativeModules.Bluetooth,
		"Brightness": NativeModules.Brightness,
		"Files": NativeModules.Files,
		"Alarm": NativeModules.Alarm,
		"Image": NativeModules.Image,
		"Video": NativeModules.Video,
		"Audio": NativeModules.Audio,
		"Sms": NativeModules.Sms,
		"Calls": NativeModules.Calls,
		"Contacts": NativeModules.Contacts,
};